#:schema node_modules/wrangler/config-schema.json
name = "lagdocs-main"
main = ".open-next/worker.js"
compatibility_date = "2024-12-19"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[routes]]
pattern = "docs.lagless.gg"
custom_domain = true


[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true